apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: netcho/bnetserver
  kaniko:
    buildContext:
      localDir: {}
    namespace: default
    pullSecretName: docker-hub
deploy:
  helm:
    releases:
    - name: aurora-production
      chartPath: ../chart/
      namespace: default
      values:
        image: netcho/bnetserver
      setValues:
        rabbitmq.rabbitmq.password: 65sdof6516
        mysql.hostname: 192.168.1.4
        mysql.database: battlenet