{{- $fullName := include "bnetserver.fullname" . }}
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "bnetserver.name" . }}-frontend
    helm.sh/chart: {{ include "bnetserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.frontend.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.frontend.ingress.tls }}
  tls:
  {{- range .Values.frontend.ingress.tls }}
  - hosts:
    {{- range .hosts }}
      - {{ . | quote }}
    {{- end }}
  secretName: {{ $fullName }}-frontend-secret
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.frontend.ingress.hosts }}
  - host: {{ . | quote }}
    tcp:
      port: '1119'
      backend:
        serviceName: {{ $fullName }}-frontend
        servicePort: '1119'
  {{- end }}
