apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "bnetserver.fullname" . }}-rest
  labels:
    app.kubernetes.io/name: {{ include "bnetserver.name" . }}
    helm.sh/chart: {{ include "bnetserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.rest.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bnetserver.name" . }}-rest
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bnetserver.name" . }}-rest
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: rest
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["npm"]
          args: ["run", "rest"]
          env:
            - name: ZOOKEEPER_ADDRESS
              value: {{ .Release.Name }}-zookeeper
            - name: NODE_ENV
              value: {{ .Values.env }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/config
            - name: logs
              mountPath: /usr/src/app/logs
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              initialDelaySeconds: 10
              periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
              initialDelaySeconds: 10
              periodSeconds: 30
          resources:
{{ toYaml .Values.rest.resources | indent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "bnetserver.fullname" . }}-config
            items:
              - key: database.json
                path: database.json
              - key: winston.json
                path: winston.json
        - name: logs
          emptyDir: {}
    {{- with .Values.rest.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.rest.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.rest.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
